### ISSUE TITLE
outputコマンドの作成

### ISSUE THREAD

**Issue by iwbchi** [conea0/course-library-cli#13]
## やること
- mdからjsonを抜き出す
- jsonを更新する
- 変更後のmdを返す

**Comment by syuya2036** [comment]
## 仕様変更
### before
- mdをパースしてoutputに変更を加え、それを元のmdに上書きする
### after
- mdに上書きではなく、新しいjsonファイルに出力する

**Comment by syuya2036** [comment]
## 仕様変更
### before
- 問題文の出力はjson
### after 
- yaml

**Comment by syuya2036** [comment]
## 仕様変更
テストケースの型を以下のように変更
```go
type Test struct {
	Input  *[]any `json:"input"`
	Output *string   `json:"output"`
}
```
### 理由
inputにintが入ることもあるため。
